version: '3'
services:
  mongodb:
    image: 'mongo:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '8080:80'
  api:
    build:
      context: ./server
    volumes:
      - /app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=test
  client:
    build:
      context: ./client
    volumes:
      - /app/node_modules
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      context: ./worker
    volumes:
      - /app/node_modules

 